#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
#set -o xtrace

main() {
  if [ ! "$(docker ps -q -f name=mypg)" ]; then
    if [ "$(docker ps -aq -f status=exited -f name=mypg)" ]; then
      docker start mypg
    else
      docker run -d --name mypg \
        -e POSTGRES_PASSWORD=postgres \
        -e POSTGRES_USER=postgres \
        -e POSTGRES_DB=my-db \
        -p 5432:5432 \
          postgres:13
    fi
  fi
}

main
exit 0
